server:
  port: 3000
  compression:
    enabled: true
  connection:
    timeout: -1
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

